/**
 * The generated site's stylesheet. Hand-written, no framework, no build step.
 *
 * The look is deliberately stock: rounded cards, soft shadows, centred hero,
 * pill buttons. "Respectable and hollow." Layout variations hang off a
 * `layout-*` class on <body>.
 */

import type { Answers, GenerateOptions } from "./types";
import { getPalette } from "./presets/palettes";
import { getFontStyle } from "./presets/fontStyles";
import { cssUrl } from "./escape";

export const FONT_DIR = "assets/fonts";

export function buildCss(answers: Answers, resolveAsset: NonNullable<GenerateOptions["resolveAsset"]>): string {
  const palette = getPalette(answers.palette);
  const font = getFontStyle(answers.fontStyle);
  const c = palette.colors;

  const fontFaces = font.files
    .map(
      (f) =>
        `@font-face {\n  font-family: "${f.family}";\n  font-style: normal;\n  font-weight: ${f.weight};\n  font-display: swap;\n  src: url("${cssUrl(resolveAsset(`${FONT_DIR}/${f.file}`))}") format("woff2");\n}`,
    )
    .join("\n");

  return `/* Generated by The Floor. Plain CSS, no framework. */
${fontFaces ? fontFaces + "\n" : ""}
:root {
  --color-primary: ${c.primary};
  --color-on-primary: ${c.onPrimary};
  --color-accent: ${c.accent};
  --color-on-accent: ${c.onAccent};
  --color-bg: ${c.bg};
  --color-surface: ${c.surface};
  --color-text: ${c.text};
  --color-muted: ${c.muted};
  --color-border: ${c.border};
  --font-heading: ${font.headingFamily};
  --font-body: ${font.bodyFamily};
  --heading-weight: ${font.headingWeight};
  --radius: 14px;
  --shadow: 0 10px 30px rgba(0, 0, 0, 0.08);
  --container: 1120px;
}

/* ---------- Base ---------- */
*, *::before, *::after { box-sizing: border-box; }
html { -webkit-text-size-adjust: 100%; }
body {
  margin: 0;
  font-family: var(--font-body);
  font-size: 1rem;
  line-height: 1.65;
  color: var(--color-text);
  background: var(--color-bg);
}
img { max-width: 100%; height: auto; display: block; }
a { color: var(--color-primary); }
h1, h2, h3, h4 {
  font-family: var(--font-heading);
  font-weight: var(--heading-weight);
  line-height: 1.2;
  margin: 0 0 0.5em;
}
h1 { font-size: clamp(2.1rem, 5vw, 3.4rem); }
h2 { font-size: clamp(1.6rem, 3.2vw, 2.3rem); }
h3 { font-size: 1.25rem; }
p { margin: 0 0 1em; }
p:last-child { margin-bottom: 0; }
.container { width: min(var(--container), 100% - 2.5rem); margin-inline: auto; }
.section { padding: clamp(3rem, 7vw, 5.5rem) 0; }
.section--surface { background: var(--color-surface); }
.section-title { text-align: center; max-width: 680px; margin: 0 auto 2.75rem; }
.section-title p { color: var(--color-muted); font-size: 1.1rem; }
.muted { color: var(--color-muted); }
.button {
  display: inline-block;
  padding: 0.95rem 2rem;
  border-radius: 999px;
  background: var(--color-accent);
  color: var(--color-on-accent);
  font-weight: 700;
  text-decoration: none;
  border: 2px solid transparent;
  transition: transform 0.15s ease, box-shadow 0.15s ease;
}
.button:hover { transform: translateY(-2px); box-shadow: var(--shadow); }
.button--outline { background: transparent; color: inherit; border-color: currentColor; }
.button--primary { background: var(--color-primary); color: var(--color-on-primary); }
:focus-visible { outline: 3px solid var(--color-accent); outline-offset: 3px; }

/* ---------- Header ---------- */
.site-header {
  position: sticky;
  top: 0;
  z-index: 10;
  background: var(--color-bg);
  border-bottom: 1px solid var(--color-border);
}
.header-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
  min-height: 74px;
  flex-wrap: wrap;
}
.brand {
  display: inline-flex;
  align-items: center;
  gap: 0.6rem;
  font-family: var(--font-heading);
  font-weight: var(--heading-weight);
  font-size: 1.4rem;
  color: var(--color-text);
  text-decoration: none;
  line-height: 1.1;
}
.brand img { height: 46px; width: auto; max-width: 220px; object-fit: contain; }
.site-nav { display: none; width: 100%; flex-direction: column; padding: 0.25rem 0 1rem; }
.site-nav a {
  padding: 0.7rem 0;
  color: var(--color-text);
  text-decoration: none;
  font-weight: 600;
  border-bottom: 1px solid var(--color-border);
}
.site-nav a[aria-current="page"] { color: var(--color-primary); }
.menu-toggle summary {
  list-style: none;
  cursor: pointer;
  width: 44px;
  height: 44px;
  display: grid;
  place-items: center;
  border-radius: 8px;
}
.menu-toggle summary::-webkit-details-marker { display: none; }
.bars, .bars::before, .bars::after {
  display: block;
  width: 22px;
  height: 2px;
  background: var(--color-text);
  border-radius: 2px;
  position: relative;
}
.bars::before, .bars::after { content: ""; position: absolute; left: 0; }
.bars::before { top: -7px; }
.bars::after { top: 7px; }
.header-inner:has(.menu-toggle[open]) .site-nav { display: flex; }
@media (min-width: 768px) {
  .menu-toggle { display: none; }
  .site-nav { display: flex; width: auto; flex-direction: row; gap: 1.9rem; padding: 0; }
  .site-nav a { border: 0; padding: 0.25rem 0; }
  .site-nav a:hover { color: var(--color-primary); }
}

/* ---------- Hero (shared) ---------- */
.hero {
  position: relative;
  overflow: hidden;
  color: var(--color-on-primary);
  background: var(--color-primary);
}
.hero-bg {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}
.hero--image::before {
  content: "";
  position: absolute;
  inset: 0;
  background: rgba(0, 0, 0, 0.45);
  z-index: 1;
}
.hero .container { position: relative; z-index: 2; }
.hero h1 { color: inherit; }
.hero-text { font-size: 1.15rem; max-width: 640px; opacity: 0.92; margin-bottom: 2rem; }
.hero-tagline { font-size: 1rem; letter-spacing: 0.02em; opacity: 0.85; margin-bottom: 0.75rem; }

/* Layout: hero + three columns */
.layout-hero-columns .hero { text-align: center; padding: clamp(4.5rem, 13vw, 9rem) 0; }
.layout-hero-columns .hero-text { margin-inline: auto; }
.layout-hero-columns .feature { text-align: center; padding: 1rem; }
.layout-hero-columns .feature-icon {
  width: 68px;
  height: 68px;
  border-radius: 50%;
  display: grid;
  place-items: center;
  margin: 0 auto 1.1rem;
  background: var(--color-surface);
  color: var(--color-primary);
}

/* Layout: split screen */
.layout-split .hero { background: var(--color-surface); color: var(--color-text); }
.layout-split .hero::before { display: none; }
.layout-split .hero-grid {
  display: grid;
  gap: 2.5rem;
  align-items: center;
  padding: clamp(3rem, 8vw, 6rem) 0;
}
.layout-split .hero-img {
  width: 100%;
  aspect-ratio: 4 / 3;
  object-fit: cover;
  border-radius: var(--radius);
  box-shadow: var(--shadow);
}
.layout-split .hero-img--placeholder { background: var(--color-primary); }
.layout-split .hero-tagline { color: var(--color-primary); opacity: 1; font-weight: 700; }
.layout-split .hero-text { color: var(--color-muted); opacity: 1; }
.layout-split .feature { border-top: 3px solid var(--color-accent); padding-top: 1.25rem; }
.layout-split .feature-icon { color: var(--color-primary); margin-bottom: 0.75rem; }
@media (min-width: 768px) {
  .layout-split .hero-grid { grid-template-columns: 1fr 1fr; gap: 4rem; }
}

/* Layout: big image banner */
.layout-banner .hero { min-height: min(82vh, 760px); display: flex; align-items: flex-end; }
.layout-banner .hero--image::before {
  background: linear-gradient(to top, rgba(0, 0, 0, 0.7) 0%, rgba(0, 0, 0, 0.25) 60%, rgba(0, 0, 0, 0.1) 100%);
}
.layout-banner .hero .container { padding: clamp(3rem, 8vw, 6rem) 0 clamp(5rem, 10vw, 8rem); }
.layout-banner .hero h1 { font-size: clamp(2.4rem, 6.5vw, 4.5rem); max-width: 14ch; }
.layout-banner .features-strip {
  margin-top: -3.5rem;
  position: relative;
  z-index: 3;
  background: var(--color-bg);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
  padding: 2rem 1.5rem;
}
.layout-banner .feature { padding: 0.5rem 1rem; }
.layout-banner .feature-icon { color: var(--color-accent); margin-bottom: 0.5rem; }
.layout-banner .features-section { padding-bottom: clamp(3rem, 7vw, 5.5rem); }
@media (min-width: 768px) {
  .layout-banner .features-strip .features { gap: 0; }
  .layout-banner .feature + .feature { border-left: 1px solid var(--color-border); }
}

/* Layout: card grid */
.layout-cards .hero { text-align: center; padding: clamp(3rem, 8vw, 5rem) 0; }
.layout-cards .hero-text { margin-inline: auto; }
.layout-cards .feature {
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
  padding: 1.75rem;
}
.layout-cards .feature-icon {
  width: 52px;
  height: 52px;
  border-radius: 12px;
  display: grid;
  place-items: center;
  background: var(--color-primary);
  color: var(--color-on-primary);
  margin-bottom: 1rem;
}
.layout-cards .features-section { background: var(--color-surface); }

/* ---------- Features ---------- */
.features { display: grid; gap: 2rem; }
.feature h3 { margin-bottom: 0.4rem; }
.feature p { color: var(--color-muted); }
@media (min-width: 640px) { .features { grid-template-columns: repeat(3, 1fr); } }

/* ---------- CTA band ---------- */
.cta-band { background: var(--color-primary); color: var(--color-on-primary); text-align: center; }
.cta-band h2 { color: inherit; }
.cta-band p { opacity: 0.9; max-width: 560px; margin: 0 auto 1.75rem; }
.cta-band .button { background: var(--color-bg); color: var(--color-primary); }
.layout-split .cta-band { background: var(--color-text); color: var(--color-bg); }
.layout-split .cta-band .button { color: var(--color-text); }

/* ---------- Inner pages ---------- */
.page-header { padding: clamp(2.5rem, 6vw, 4.5rem) 0; background: var(--color-surface); }
.page-header h1 { margin-bottom: 0.25rem; }
.page-header p { color: var(--color-muted); font-size: 1.1rem; }
.layout-banner .page-header, .layout-cards .page-header { background: var(--color-primary); color: var(--color-on-primary); }
.layout-banner .page-header p, .layout-cards .page-header p { color: inherit; opacity: 0.85; }
.layout-hero-columns .page-header, .layout-cards .page-header { text-align: center; }
.prose { max-width: 720px; }
.prose p { font-size: 1.08rem; }
.layout-hero-columns .prose { margin-inline: auto; }

/* Team */
.team { display: grid; gap: 1.5rem; margin-top: 1rem; }
.team-member {
  display: flex;
  align-items: center;
  gap: 1rem;
  background: var(--color-surface);
  border-radius: var(--radius);
  padding: 1.25rem;
}
.avatar {
  flex: none;
  width: 60px;
  height: 60px;
  border-radius: 50%;
  display: grid;
  place-items: center;
  background: var(--color-primary);
  color: var(--color-on-primary);
  font-family: var(--font-heading);
  font-weight: var(--heading-weight);
  font-size: 1.25rem;
}
.team-member h3 { margin: 0; font-size: 1.1rem; }
.team-member p { margin: 0; color: var(--color-muted); }
@media (min-width: 640px) { .team { grid-template-columns: repeat(2, 1fr); } }

/* Services */
.services { display: grid; gap: 1.5rem; }
.service {
  display: flex;
  flex-direction: column;
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  padding: 1.75rem;
  box-shadow: var(--shadow);
}
.service h3 { margin-bottom: 0.4rem; }
.service p { color: var(--color-muted); flex: 1; }
.service-price {
  margin-top: 1rem;
  padding-top: 1rem;
  border-top: 1px solid var(--color-border);
  font-weight: 700;
  color: var(--color-primary);
}
@media (min-width: 640px) { .services { grid-template-columns: repeat(2, 1fr); } }
@media (min-width: 960px) { .services { grid-template-columns: repeat(3, 1fr); } }

/* Gallery */
.gallery { display: grid; gap: 1rem; grid-template-columns: repeat(2, 1fr); }
.gallery img, .gallery-placeholder {
  width: 100%;
  aspect-ratio: 4 / 3;
  object-fit: cover;
  border-radius: var(--radius);
}
.gallery-placeholder {
  display: grid;
  place-items: center;
  background: var(--color-surface);
  color: var(--color-muted);
  border: 1px dashed var(--color-border);
  text-align: center;
  padding: 1rem;
  font-size: 0.95rem;
}
.gallery-placeholder svg { margin-bottom: 0.5rem; opacity: 0.6; }
@media (min-width: 768px) { .gallery { grid-template-columns: repeat(3, 1fr); gap: 1.25rem; } }

/* Contact */
.contact-grid { display: grid; gap: 2.5rem; }
.contact-list { list-style: none; padding: 0; margin: 0; display: grid; gap: 1.25rem; }
.contact-list li { display: flex; gap: 0.9rem; align-items: flex-start; }
.contact-list svg { flex: none; color: var(--color-primary); margin-top: 0.15rem; }
.contact-list strong { display: block; margin-bottom: 0.15rem; }
.contact-list a { color: var(--color-text); }
.contact-form {
  background: var(--color-surface);
  border-radius: var(--radius);
  padding: 2rem;
}
.contact-form label { display: block; font-weight: 600; margin-bottom: 0.35rem; }
.contact-form input, .contact-form textarea {
  width: 100%;
  font: inherit;
  padding: 0.8rem 0.9rem;
  border: 1px solid var(--color-border);
  border-radius: 8px;
  background: var(--color-bg);
  color: var(--color-text);
  margin-bottom: 1.1rem;
}
.contact-form textarea { min-height: 140px; resize: vertical; }
.contact-form button {
  font: inherit;
  cursor: pointer;
}
@media (min-width: 860px) { .contact-grid { grid-template-columns: 1fr 1.2fr; gap: 4rem; } }

/* ---------- Footer ---------- */
.site-footer { background: var(--color-text); color: var(--color-bg); padding: 2.5rem 0; margin-top: auto; }
.footer-inner { display: flex; flex-direction: column; gap: 1rem; align-items: center; text-align: center; }
.footer-inner p { margin: 0; opacity: 0.8; font-size: 0.95rem; }
.footer-nav { display: flex; flex-wrap: wrap; justify-content: center; gap: 1.25rem; }
.footer-nav a { color: inherit; text-decoration: none; opacity: 0.85; }
.footer-nav a:hover { opacity: 1; text-decoration: underline; }
@media (min-width: 768px) {
  .footer-inner { flex-direction: row; justify-content: space-between; text-align: left; }
}

/* ---------- Motion ---------- */
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after { transition: none !important; }
}
`;
}
