// Generated by scripts/build-examples.cjs. Do not edit by hand.
// Ten demo sites, each built through the wizard by someone playing a small
// business owner. The businesses are invented; the sites are the real output.
export interface ExampleCredit {
  title: string;
  author: string;
  license: string;
  licenseUrl: string;
  filePage: string;
}
export interface Example {
  slug: string;
  title: string;
  trade: string;
  blurb: string;
  layout: string;
  palette: string;
  font: string;
  pages: string[];
  photos: number;
  sizeKB: number;
  credits: ExampleCredit[];
  unsplash: boolean;
}

export const EXAMPLES: readonly Example[] = [
  {
    "slug": "black-iris-tattoo",
    "title": "Black Iris Tattoo",
    "trade": "Tattoo studio",
    "blurb": "Dark, appointment only, and deliberately missing a services page.",
    "layout": "Big image",
    "palette": "Midnight",
    "font": "Modern",
    "pages": [
      "Home",
      "About",
      "Gallery",
      "Contact"
    ],
    "photos": 7,
    "sizeKB": 3653,
    "credits": [
      {
        "title": "Italian-tattoo-artist-at-work.jpg",
        "author": "Technopop.tattoo",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AItalian-tattoo-artist-at-work.jpg"
      },
      {
        "title": "Archives of American Art - Members of the W.P.A. Federal Art Project art class at the Seamen's Institute. - 12272.jpg",
        "author": "David Robbins",
        "license": "Public domain",
        "licenseUrl": "",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AArchives_of_American_Art_-_Members_of_the_W.P.A._Federal_Art_Project_art_class_at_the_Seamen's_Institute._-_12272.jpg"
      },
      {
        "title": "'Rollomatic' liner.JPG",
        "author": "Haa900",
        "license": "CC0",
        "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "filePage": "https://commons.wikimedia.org/wiki/File%3A'Rollomatic'_liner.JPG"
      },
      {
        "title": "Phoenix full sleeve tattoo by Maaika.jpg",
        "author": "InvestigadorDeTodo",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3APhoenix_full_sleeve_tattoo_by_Maaika.jpg"
      },
      {
        "title": "Woman getting a tattoo at the International Brussels Tattoo Convention 2023.jpg",
        "author": "Miguel Discart",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AWoman_getting_a_tattoo_at_the_International_Brussels_Tattoo_Convention_2023.jpg"
      },
      {
        "title": "Woman getting a tattoo at the International Brussels Tattoo Convention 2023.jpg",
        "author": "Miguel Discart",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AWoman_getting_a_tattoo_at_the_International_Brussels_Tattoo_Convention_2023.jpg"
      },
      {
        "title": "International Brussels Tattoo Convention 2018 03.jpg",
        "author": "miguel.discart",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AInternational_Brussels_Tattoo_Convention_2018_03.jpg"
      }
    ],
    "unsplash": false
  },
  {
    "slug": "bright-start-tutoring",
    "title": "Bright Start Tutoring",
    "trade": "Private tutor",
    "blurb": "Didn't want photographs of other people's children, so the site runs on words alone.",
    "layout": "",
    "palette": "",
    "font": "",
    "pages": [
      "About",
      "Contact",
      "Home",
      "Services"
    ],
    "photos": 2,
    "sizeKB": 1489,
    "credits": [
      {
        "title": "New Desk in use (15550685686).jpg",
        "author": "brewbooks from near Seattle, USA",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ANew_Desk_in_use_(15550685686).jpg"
      },
      {
        "title": "Hardy Boys books on a public library shelf.jpg",
        "author": "Jengod",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AHardy_Boys_books_on_a_public_library_shelf.jpg"
      }
    ],
    "unsplash": false
  },
  {
    "slug": "corner-bakery",
    "title": "Corner Bakery",
    "trade": "Bakery",
    "blurb": "One small batch a morning, sold until it's gone. The photos do the selling.",
    "layout": "Hero + three",
    "palette": "Sand",
    "font": "Classic",
    "pages": [
      "Home",
      "About",
      "Services",
      "Gallery",
      "Contact"
    ],
    "photos": 8,
    "sizeKB": 3832,
    "credits": [
      {
        "title": "Sourdough bread - January 2026 - Sarah Stierch 03.jpg",
        "author": "Missvain",
        "license": "CC0",
        "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ASourdough_bread_-_January_2026_-_Sarah_Stierch_03.jpg"
      },
      {
        "title": "Skansen 2019 13 49 49 597000.jpeg",
        "author": "Salgo60",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ASkansen_2019_13_49_49_597000.jpeg"
      },
      {
        "title": "Croissant In Austria.jpg",
        "author": "בר",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ACroissant_In_Austria.jpg"
      },
      {
        "title": "Bowl with bread loaves and persea twigs, baked clay, vegetable fibers - Museo Egizio, Turin S 8359 p04.jpg",
        "author": "Unknown",
        "license": "CC0",
        "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ABowl_with_bread_loaves_and_persea_twigs%2C_baked_clay%2C_vegetable_fibers_-_Museo_Egizio%2C_Turin_S_8359_p04.jpg"
      },
      {
        "title": "Bowl with bread loaves and persea twigs, clay - Museo Egizio (Turin) S 8359 p04.jpg",
        "author": "Unknown",
        "license": "CC0",
        "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ABowl_with_bread_loaves_and_persea_twigs%2C_clay_-_Museo_Egizio_(Turin)_S_8359_p04.jpg"
      },
      {
        "title": "(Artisan bread).JPG",
        "author": "David Adam Kess",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3A(Artisan_bread).JPG"
      },
      {
        "title": "Bread for canapés at the SF Chronicle Wine competition Public tasting 2010-02-20.jpg",
        "author": "Guillaume Paumier",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ABread_for_canap%C3%A9s_at_the_SF_Chronicle_Wine_competition_Public_tasting_2010-02-20.jpg"
      },
      {
        "title": "Statuette of a baker kneading dough 01.jpg",
        "author": "ArchaiOptix",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AStatuette_of_a_baker_kneading_dough_01.jpg"
      }
    ],
    "unsplash": false
  },
  {
    "slug": "greenline-landscaping",
    "title": "Greenline Landscaping",
    "trade": "Landscaper",
    "blurb": "Built on an iPad. The gallery of finished gardens is the whole pitch.",
    "layout": "Hero + three",
    "palette": "Forest",
    "font": "Plain",
    "pages": [
      "Home",
      "About",
      "Services",
      "Gallery",
      "Contact"
    ],
    "photos": 6,
    "sizeKB": 6634,
    "credits": [
      {
        "title": "Patio paving Capel Manor College Gardens Enfield London England 02.jpg",
        "author": "Acabashi",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3APatio_paving_Capel_Manor_College_Gardens_Enfield_London_England_02.jpg"
      },
      {
        "title": "Southwater Cricket Club pavilion at Southwater, West Sussex, England 2.jpg",
        "author": "Acabashi",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ASouthwater_Cricket_Club_pavilion_at_Southwater%2C_West_Sussex%2C_England_2.jpg"
      },
      {
        "title": "Zentralbibliothek Zürich - Blumengruppe b. d. Kirche Enge - 991051956319705501.jpg",
        "author": "Robert Breitinger",
        "license": "Public domain",
        "licenseUrl": "",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AZentralbibliothek_Z%C3%BCrich_-_Blumengruppe_b._d._Kirche_Enge_-_991051956319705501.jpg"
      },
      {
        "title": "Zentralbibliothek Zürich - Hotel Baur Garten Fächer - 991051919819705501.jpg",
        "author": "Robert Breitinger",
        "license": "Public domain",
        "licenseUrl": "",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AZentralbibliothek_Z%C3%BCrich_-_Hotel_Baur_Garten_F%C3%A4cher_-_991051919819705501.jpg"
      },
      {
        "title": "Green Lawn Garden Mausoleum 02 - Green Lawn Cemetery.jpg",
        "author": "Tim Evanson",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AGreen_Lawn_Garden_Mausoleum_02_-_Green_Lawn_Cemetery.jpg"
      },
      {
        "title": "Princes street garden hedges in Edinburgh.jpg",
        "author": "Cbuske46",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3APrinces_street_garden_hedges_in_Edinburgh.jpg"
      }
    ],
    "unsplash": false
  },
  {
    "slug": "hartley-accounting",
    "title": "Hartley & Co",
    "trade": "Accountants",
    "blurb": "Decided stock photos of handshakes looked fake and used none at all. The hero is a flat block of colour.",
    "layout": "",
    "palette": "",
    "font": "",
    "pages": [
      "About",
      "Contact",
      "Home",
      "Services"
    ],
    "photos": 2,
    "sizeKB": 1319,
    "credits": [
      {
        "title": "Inbox trays.jpg",
        "author": "Khairil Yusof",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AInbox_trays.jpg"
      },
      {
        "title": "Merida Yucatan - Consulate Office Building, Secretarial Desk - 1977.jpg",
        "author": "photographer not credited",
        "license": "Public domain",
        "licenseUrl": "",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AMerida_Yucatan_-_Consulate_Office_Building%2C_Secretarial_Desk_-_1977.jpg"
      }
    ],
    "unsplash": false
  },
  {
    "slug": "lena-marsh-photography",
    "title": "Lena Marsh Photography",
    "trade": "Photographer",
    "blurb": "Nine photographs at full size, because for a photographer the pictures are the product.",
    "layout": "Big image",
    "palette": "Wine",
    "font": "Elegant",
    "pages": [
      "Home",
      "About",
      "Services",
      "Gallery",
      "Contact"
    ],
    "photos": 10,
    "sizeKB": 7875,
    "credits": [
      {
        "title": "Christian wedding in Russia.jpg",
        "author": "Виктория Злых",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AChristian_wedding_in_Russia.jpg"
      },
      {
        "title": "Wedding couple holding hands closeup.jpg",
        "author": "Shixart1985",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AWedding_couple_holding_hands_closeup.jpg"
      },
      {
        "title": "Long Wedding Dress for Couple with Flowers.jpg",
        "author": "epSos.de",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ALong_Wedding_Dress_for_Couple_with_Flowers.jpg"
      },
      {
        "title": "Wedding reception at InterContinental Yokohama Grand.jpg",
        "author": "Syced",
        "license": "CC0",
        "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AWedding_reception_at_InterContinental_Yokohama_Grand.jpg"
      },
      {
        "title": "Placing a wedding ring.jpg",
        "author": "Petar Milošević",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3APlacing_a_wedding_ring.jpg"
      },
      {
        "title": "The bridal night by James Gillray.jpg",
        "author": "James Gillray",
        "license": "Public domain",
        "licenseUrl": "",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AThe_bridal_night_by_James_Gillray.jpg"
      },
      {
        "title": "Marten van Cleve the Elder (Workshop of) Departure of the wedding guests.jpg",
        "author": "Workshop of Marten van Cleve",
        "license": "Public domain",
        "licenseUrl": "",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AMarten_van_Cleve_the_Elder_(Workshop_of)_Departure_of_the_wedding_guests.jpg"
      },
      {
        "title": "Travellers at Wedding Cake Rock, December 2014.jpg",
        "author": "Philip Terry Graham",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ATravellers_at_Wedding_Cake_Rock%2C_December_2014.jpg"
      },
      {
        "title": "Kahan's engagement party in Tel Aviv (FL45976436).jpg",
        "author": "IPPA photographer",
        "license": "CC BY 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AKahan's_engagement_party_in_Tel_Aviv_(FL45976436).jpg"
      },
      {
        "title": "Families walking, Combe Abbey - geograph.org.uk - 8186792.jpg",
        "author": "Robin Stott",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AFamilies_walking%2C_Combe_Abbey_-_geograph.org.uk_-_8186792.jpg"
      }
    ],
    "unsplash": false
  },
  {
    "slug": "muddy-paws",
    "title": "Muddy Paws",
    "trade": "Mobile dog groomer",
    "blurb": "A grooming van with no fixed address, so the phone number goes everywhere.",
    "layout": "Card grid",
    "palette": "Ocean",
    "font": "Modern",
    "pages": [
      "Home",
      "About",
      "Services",
      "Gallery",
      "Contact"
    ],
    "photos": 3,
    "sizeKB": 2174,
    "credits": [
      {
        "title": "Grooming Poodle.jpg",
        "author": "daveynin",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AGrooming_Poodle.jpg"
      },
      {
        "title": "Grooming Poodle.jpg",
        "author": "daveynin",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AGrooming_Poodle.jpg"
      },
      {
        "title": "Drevvikens naturreservat, södra delen, maj 2019e.jpg",
        "author": "Holger.Ellgaard",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ADrevvikens_naturreservat%2C_s%C3%B6dra_delen%2C_maj_2019e.jpg"
      }
    ],
    "unsplash": false
  },
  {
    "slug": "riverside-players",
    "title": "Riverside Players",
    "trade": "Amateur theatre group",
    "blurb": "A volunteer secretary, a village hall, and fifty years of shows.",
    "layout": "Hero + three",
    "palette": "Navy",
    "font": "Classic",
    "pages": [
      "Home",
      "About",
      "Services",
      "Gallery",
      "Contact"
    ],
    "photos": 9,
    "sizeKB": 5747,
    "credits": [
      {
        "title": "Küçük Tiyatro.jpg",
        "author": "Gargarapalvin",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AK%C3%BC%C3%A7%C3%BCk_Tiyatro.jpg"
      },
      {
        "title": "The theatre stage and auditorium of the Peacock Performing Arts Center in Hayesville, North Carolina 02.jpg",
        "author": "Harrison Keely",
        "license": "CC BY 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AThe_theatre_stage_and_auditorium_of_the_Peacock_Performing_Arts_Center_in_Hayesville%2C_North_Carolina_02.jpg"
      },
      {
        "title": "Community Theatre, Pine Bluff, Arkansas.jpg",
        "author": "Paul Sableman (Flickr user: pasa47)",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ACommunity_Theatre%2C_Pine_Bluff%2C_Arkansas.jpg"
      },
      {
        "title": "Vojtěch Hynais, Curtain of the National Theatre, Prague.jpg",
        "author": "Vojtěch Hynais",
        "license": "Public domain",
        "licenseUrl": "",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AVojt%C4%9Bch_Hynais%2C_Curtain_of_the_National_Theatre%2C_Prague.jpg"
      },
      {
        "title": "Two actors rehearse a scene from \"Almost, Maine\".jpg",
        "author": "Harrison Keely",
        "license": "CC BY 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ATwo_actors_rehearse_a_scene_from_%22Almost%2C_Maine%22.jpg"
      },
      {
        "title": "Katowice Silesian Theatre auditorium 2022.jpg",
        "author": "Adrian Tync",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AKatowice_Silesian_Theatre_auditorium_2022.jpg"
      },
      {
        "title": "Eufuria Albany Capital Center main stage Mailpup.jpg",
        "author": "Reconrabbit",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AEufuria_Albany_Capital_Center_main_stage_Mailpup.jpg"
      },
      {
        "title": "Performance in the Theatre of Epidaurus, 091068.jpg",
        "author": "Zde",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3APerformance_in_the_Theatre_of_Epidaurus%2C_091068.jpg"
      },
      {
        "title": "Namiki Square Chihaya Music and Drama Rehearsal Rooms 21-45 Chihaya 4-chōme Hiagashi-ku Fukuoka 20231102.jpg",
        "author": "Hirho",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ANamiki_Square_Chihaya_Music_and_Drama_Rehearsal_Rooms_21-45_Chihaya_4-ch%C5%8Dme_Hiagashi-ku_Fukuoka_20231102.jpg"
      }
    ],
    "unsplash": false
  },
  {
    "slug": "spoke-and-chain",
    "title": "Spoke & Chain",
    "trade": "Bike repair shop",
    "blurb": "Built on a phone between customers, in the smallest number of taps the wizard allows.",
    "layout": "",
    "palette": "",
    "font": "",
    "pages": [
      "Contact",
      "Home",
      "Services"
    ],
    "photos": 2,
    "sizeKB": 1578,
    "credits": [
      {
        "title": "Munich - Two men working in a Bicycle repair shop - 5893.jpg",
        "author": "Jorge Royan",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AMunich_-_Two_men_working_in_a_Bicycle_repair_shop_-_5893.jpg"
      },
      {
        "title": "Bicycle workshop Ruyigi.JPG",
        "author": "Andreas31",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ABicycle_workshop_Ruyigi.JPG"
      }
    ],
    "unsplash": false
  },
  {
    "slug": "still-point-yoga",
    "title": "Still Point Yoga",
    "trade": "Yoga studio",
    "blurb": "Built entirely on a phone, by someone whose students are all on phones.",
    "layout": "Split",
    "palette": "Forest",
    "font": "Classic",
    "pages": [
      "Home",
      "About",
      "Services",
      "Gallery",
      "Contact"
    ],
    "photos": 8,
    "sizeKB": 4771,
    "credits": [
      {
        "title": "Naam Yoga LA Class.jpg",
        "author": "Drmirshak",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ANaam_Yoga_LA_Class.jpg"
      },
      {
        "title": "SABDA Studio immersive room Barcelona.jpg",
        "author": "Marv0611",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ASABDA_Studio_immersive_room_Barcelona.jpg"
      },
      {
        "title": "Elkedagyoga.nl yoga studio, Alphen aan den Rijn (2022) 02.jpg",
        "author": "Donald Trung Quoc Don (Chữ Hán: 徵國單) - Wikimedia Commons - © CC BY-SA 4.0 International.(Want to use this image?)Original publication 📤: --Donald Trung 『徵國單』 (No Fake News 💬) (WikiProject Numismatics 💴) (Articles 📚) 11:47, 11 November 2022 (UTC)",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AElkedagyoga.nl_yoga_studio%2C_Alphen_aan_den_Rijn_(2022)_02.jpg"
      },
      {
        "title": "Yoga Mat Made of Carpet Underlay.jpg",
        "author": "Ian Alexander",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AYoga_Mat_Made_of_Carpet_Underlay.jpg"
      },
      {
        "title": "Meditation Centre, NISER.jpg",
        "author": "Amiwins",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AMeditation_Centre%2C_NISER.jpg"
      },
      {
        "title": "Baby yoga, Asana, Physical culture, Moscow, Russia.jpg",
        "author": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3ABaby_yoga%2C_Asana%2C_Physical_culture%2C_Moscow%2C_Russia.jpg"
      },
      {
        "title": "Koh Wai, Thailand, Yoga, Asana.jpg",
        "author": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AKoh_Wai%2C_Thailand%2C_Yoga%2C_Asana.jpg"
      },
      {
        "title": "Yoga Practices.jpg",
        "author": "Nivedita Verm",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "filePage": "https://commons.wikimedia.org/wiki/File%3AYoga_Practices.jpg"
      }
    ],
    "unsplash": false
  }
];
