/* ============================================================
   7-3 — the hundred

   People and objects scattered through the city that you can talk
   to or poke. Most just say something. Some hand over a small
   amount of money, a snack, or a bit of the day back. A few
   escalate into an actual encounter, which is the only way any of
   them can cost you anything — and even then it cannot cost much.

   P() is a person, placed as a walking NPC and given a dialect
       from voices.js when the area is generated.
   O() is an object, attached to a real piece of furniture so it
       inherits that tile's art instead of needing its own.

   opts:
     pay    multiple of one task's pay; negative to spend
     xp     multiple of one task's experience
     joy    flat joy, positive or (rarely, mildly) negative
     item   item id to drop in the bag
     fight  chance 0..1 that this turns into an encounter
     enemy  which encounter, if it does
     w      relative weight when picking what to place

   Prose is unbroken; ui.js wraps it to the box.
   ============================================================ */

const P = (id, name, zones, text, opts = {}) => ({
  id, name, kind: 'person', zones, text, ...opts,
});
const O = (id, name, zones, tile, text, opts = {}) => ({
  id, name, kind: 'object', zones, tile, text, ...opts,
});

const OFFICE = ['office_floor', 'office_lobby', 'break_room', 'meeting_room'];
const FLOOR = ['office_floor'];
const OUT = ['street', 'station'];
const SHOP = ['market', 'konbini'];

export const INTERACTIONS = [
  /* ---------- office: people ---------- */
  P('fish', 'SOMEONE AT THE MICROWAVE', ['break_room'],
    'They are reheating fish. They know. They have decided to do it anyway. There is a kind of courage in it.',
    { joy: -1, fight: 0.15, enemy: 'smalltalk', w: 1.2 }),
  P('printing400', 'A COLLEAGUE PRINTING', FLOOR,
    'Four hundred pages. They apologise as each one comes out. They do not stop.',
    { fight: 0.3, enemy: 'printer' }),
  P('loudcall', 'A MAN ON A CALL', FLOOR,
    '"Can everyone hear me? I said, can everyone hear me." Everyone can hear him. Three rows can hear him.',
    { joy: -1, fight: 0.2, enemy: 'meeting' }),
  P('it', 'THE IT PERSON', OFFICE,
    'You had turned it off and on again. It worked anyway. Neither of you mentions this.',
    { pay: 0.2, xp: 0.3, w: 1.3 }),
  P('fourfiftyeight', 'SOMEONE LEAVING AT 4:58', FLOOR,
    'Coat on. Bag packed. They have been like this since 4:31 and you respect it enormously.',
    { joy: 2 }),
  P('prodbug', 'A DEVELOPER, VERY STILL', FLOOR,
    'They have found something in production. They are not blinking. They say "it is fine" in a voice that is not fine.',
    { fight: 0.45, enemy: 'conflict', xp: 0.4 }),
  P('earlylunch', 'SOMEONE EATING LUNCH AT 11', FLOOR,
    'They started at seven. By their clock this is entirely reasonable and by yours it is a crime.',
    { joy: 1 }),
  P('tabsspaces', 'TWO PEOPLE DISAGREEING', FLOOR,
    'It is about indentation. It has been about indentation for eleven minutes. Neither will win. Both know this.',
    { xp: 0.5, fight: 0.25, enemy: 'conflict' }),
  P('newstarter', 'A NEW STARTER', OFFICE,
    'They cannot find the toilets and are too polite to ask twice. You point. They are so grateful it is almost upsetting.',
    { joy: 3, xp: 0.3, w: 1.2 }),
  P('crossword', 'SOMEONE DOING A CROSSWORD', ['break_room'],
    'Seven across. They have been on seven across since Tuesday. They do not want the answer. They want the company.',
    { joy: 2 }),
  P('cake', 'SOMEONE WITH A CAKE', ['break_room', 'office_lobby'],
    'It is nobody’s birthday. They just felt like it. A queue is forming with unusual speed.',
    { joy: 4, item: 'sandwich', w: 1.4 }),
  P('replyall', 'THE REPLY-ALL', FLOOR,
    'Two hundred people now know that they agree. Three have replied all to ask to be removed from the thread.',
    { fight: 0.5, enemy: 'inbox' }),
  P('finalv7', 'SOMEONE SAVING A FILE', FLOOR,
    'final_v7_ACTUAL_final.xlsx. They look at the name for a long moment and then save it anyway.',
    { xp: 0.4, fight: 0.2, enemy: 'report' }),
  P('contractor', 'A CONTRACTOR', OFFICE,
    'Six months here. Nobody knows which team. Nobody has asked. He is paid more than everyone and talks to no one.',
    { pay: 0.4 }),
  P('plantwaterer', 'THE PLANT PERSON', OFFICE,
    'Nobody asked them to. They do it every Friday. It is the only reason anything in here is alive.',
    { joy: 3, w: 1.2 }),
  P('asleep', 'SOMEONE ASLEEP', ['meeting_room'],
    'Upright. Eyes closed. Pen still in hand, resting on a notepad that says "ACTIONS:" and nothing else.',
    { joy: 1, xp: 0.2 }),
  P('knowseverything', 'THE ONE WHO KNOWS', OFFICE,
    'Twenty-two years. They know which lift is quicker, whose budget it comes from, and why the door on 4 is like that.',
    { pay: 0.6, xp: 0.6, w: 1.3 }),
  P('hoodie', 'A PERSON IN A HOODIE', OFFICE,
    'Might be an intern. Might be a director. You have been here long enough not to guess.',
    { xp: 0.4 }),
  P('fridgenote', 'SOMEONE WRITING A NOTE', ['break_room'],
    'They are labelling a yoghurt with their name, the date, and a short sentence about consequences.',
    { joy: -1, fight: 0.2, enemy: 'smalltalk' }),
  P('hotsauce', 'A MAN WITH SEVEN HOT SAUCES', FLOOR,
    'They live on his desk in a rack he brought from home. He offers you one. It is not a suggestion.',
    { joy: 2, item: 'energy' }),
  P('rehearsing', 'SOMEONE PRESENTING TO NOBODY', ['meeting_room'],
    'They are doing it properly. Slide transitions and everything. The room is empty. It is at 3.',
    { xp: 0.5, fight: 0.3, enemy: 'meeting' }),
  P('afteryou', 'SOMEONE IN A DOORWAY', OFFICE,
    'You both stop. You both start. You both stop. On the third attempt you go through together, sideways, like crabs.',
    { joy: 2, w: 1.3 }),
  P('birthdaycard', 'A CIRCULATING CARD', OFFICE,
    'You do not know Dominic. You sign it anyway: "Happy birthday! From the 3rd floor."',
    { joy: 1, pay: -0.2 }),
  P('leaving', 'SOMEONE ON THEIR LAST DAY', OFFICE,
    'They are clearing a drawer of things they never once used. They seem lighter than you have ever seen them.',
    { joy: 3, xp: 0.5 }),
  P('twohats', 'SOMEONE WEARING TWO LANYARDS', OFFICE,
    'One is expired. One is for a company that no longer exists. Neither opens anything. Both are worn with pride.',
    { xp: 0.3, joy: 1 }),
  P('standing', 'SOMEONE AT A STANDING DESK', FLOOR,
    'Up since nine. Committed. Visibly regretting it since about ten past.',
    { joy: 1 }),

  /* ---------- office: objects ---------- */
  O('yoghurt', 'THE FRIDGE', ['break_room'], 'FREEZER',
    'There is a yoghurt in here from March. Nobody will move it. It has become a landmark.',
    { joy: -1, fight: 0.15, enemy: 'coffee' }),
  O('pinkprinter', 'A PRINTER', OFFICE, 'PRINTER',
    'It prints everything slightly pink. IT has been told. IT has logged it. It is now simply how this printer is.',
    { fight: 0.4, enemy: 'printer', xp: 0.3, w: 1.3 }),
  O('whiteboard', 'A WHITEBOARD', ['meeting_room'], 'WHITEBOARD',
    'Someone has written DO NOT ERASE under a diagram from 2019. Nobody knows what it means. Nobody erases it.',
    { xp: 0.4 }),
  O('brokenchair', 'A CHAIR', OFFICE, 'CHAIR',
    'A sign on it reads DO NOT USE. Someone is using it. They nod at you, defiant.',
    { joy: 1 }),
  O('suggestion', 'A SUGGESTION BOX', ['office_lobby'], 'COUNTER',
    'Empty. Locked. The slot has been taped over. It has been on the wall for nine years.',
    { xp: 0.3, joy: -1 }),
  O('extinguisher', 'A FIRE EXTINGUISHER', OFFICE, 'WALL',
    'Last inspected 2003. You look at it. It looks at you. Neither of you raises it with anyone.',
    { xp: 0.2 }),
  O('mailstack', 'A STACK OF POST', ['office_lobby'], 'COUNTER',
    'Addressed to people who left. One is addressed to a company that bought this one, twice ago.',
    { pay: 0.5, fight: 0.3, enemy: 'expenses' }),
  O('poster', 'A MOTIVATIONAL POSTER', OFFICE, 'WALL',
    'A rower at dawn. The word is TEAMWORK. One corner has come away and nobody has ever fixed it.',
    { joy: -1, xp: 0.2 }),
  O('stapler', 'THE STAPLER', FLOOR, 'DESK',
    'The one that works. It has been written on in three different hands, each claiming a different floor.',
    { pay: 0.3, joy: 1 }),
  O('phone', 'A DESK PHONE', FLOOR, 'DESK',
    'It rings once a day at 2:15. Nobody has ever reached it in time. Nobody knows who is calling.',
    { fight: 0.35, enemy: 'meeting' }),
  O('lostproperty', 'LOST PROPERTY', ['office_lobby'], 'COUNTER',
    'Eleven umbrellas, one glove, and a single enormous shoe. You take an umbrella. It is raining somewhere.',
    { item: 'aspirin', joy: 1 }),
  O('rowc', 'THE VENDING MACHINE', OFFICE, 'VENDING',
    'Row C is sold out. Row C has been sold out since you started. You press C anyway. You always do.',
    { fight: 0.25, enemy: 'checkout', w: 1.2 }),
  O('coffeemachine', 'THE COFFEE MACHINE', ['break_room'], 'COOLER',
    'There is a laminated sheet of instructions, annotated by four people, each angrier than the last.',
    { item: 'coffee', xp: 0.3, w: 1.4 }),
  O('fakeplant', 'A PLANT', OFFICE, 'PLANT',
    'You have never been sure. You touch a leaf. Still not sure. That is somehow worse than either answer.',
    { joy: 1 }),
  O('window', 'A WINDOW', OFFICE, 'WALL',
    'It does not open. A small brass plate explains that this is for your safety.',
    { joy: -1, xp: 0.3 }),
  O('cables', 'UNDER A DESK', FLOOR, 'DESK',
    'A nest of cables. At least two go nowhere. At least one is warm. You back out slowly.',
    { fight: 0.3, enemy: 'conflict' }),
  O('fastclock', 'THE WALL CLOCK', OFFICE, 'WALL',
    'Seven minutes fast. Everyone knows. Everyone still panics for a moment every single time.',
    { xp: 0.4, fight: 0.2, enemy: 'deadline' }),
  O('pingpong', 'A PING PONG TABLE', ['break_room'], 'TABLE',
    'No balls. No bats. Currently in use as a place to put a printer that is going to be fixed.',
    { joy: -1, xp: 0.2 }),
  O('themug', 'THE SINK', ['break_room'], 'COUNTER',
    'One mug, four days. Everyone has decided it is not theirs, which cannot possibly be true.',
    { joy: -1, fight: 0.2, enemy: 'coffee' }),
  O('firstaid', 'A FIRST AID BOX', OFFICE, 'WALL',
    'Two plasters and a triangular bandage nobody could use. You take a plaster you do not need.',
    { item: 'aspirin' }),
  O('kettle', 'THE KETTLE', ['break_room'], 'COOLER',
    'Boiled four minutes ago by someone who then walked away and forgot. It is still, technically, yours now.',
    { item: 'coffee', joy: 2 }),
  O('bookshelf', 'A SHELF OF MANUALS', OFFICE, 'SHELF',
    'For software that was decommissioned before you arrived. Nobody will be the one to bin them.',
    { xp: 0.4, pay: 0.2 }),

  /* ---------- office equipment ---------- */
  O('yourpc', 'A COMPUTER', OFFICE, 'COMPUTER',
    'Forty tabs. Two of them are playing audio. You will never find which two.',
    { fight: 0.3, enemy: 'conflict', xp: 0.4, w: 1.4 }),
  O('spinner', 'A COMPUTER, THINKING', FLOOR, 'COMPUTER',
    'The little wheel has been turning for four minutes. You have decided to respect it rather than interrupt it.',
    { xp: 0.5, fight: 0.25, enemy: 'deadline' }),
  O('faxmachine', 'A FAX MACHINE', OFFICE, 'FAX',
    'Still plugged in. Still occasionally used. Nobody can tell you by whom, or for what.',
    { pay: 0.5, xp: 0.3, w: 1.2 }),
  O('faxreceived', 'THE FAX MACHINE', OFFICE, 'FAX',
    'Something came through overnight. It is a single page, entirely black, from a number nobody recognises.',
    { fight: 0.35, enemy: 'inbox', xp: 0.4 }),
  O('photocopier', 'THE PHOTOCOPIER', OFFICE, 'COPIER',
    'Someone has left the original on the glass. It is a payslip. You close the lid without looking. You looked.',
    { joy: 1, fight: 0.3, enemy: 'printer', w: 1.3 }),
  O('copierqueue', 'THE PHOTOCOPIER', OFFICE, 'COPIER',
    'Nine hundred and forty pages queued by somebody who then went to lunch.',
    { fight: 0.45, enemy: 'printer' }),
  O('filing', 'A FILING CABINET', OFFICE, 'CABINET',
    'The bottom drawer does not open. Everyone agrees it does not open. Nobody has ever tried very hard.',
    { pay: 0.6, xp: 0.3 }),
  O('filingempty', 'A FILING CABINET', OFFICE, 'CABINET',
    'Entirely empty except for one paperclip and a takeaway menu for a place that shut in 2011.',
    { pay: 0.3, joy: 1 }),
  O('shredder', 'THE SHREDDER', OFFICE, 'SHREDDER',
    'Deeply, unreasonably satisfying. You look for something else to shred. You find something. It was probably fine.',
    { joy: 4, xp: 0.3, w: 1.3 }),
  O('shredderfull', 'THE SHREDDER', OFFICE, 'SHREDDER',
    'Full. A small sign says EMPTY WHEN FULL. It has been full since before the sign.',
    { joy: -1, fight: 0.2, enemy: 'expenses' }),
  O('microwave', 'THE MICROWAVE', ['break_room'], 'MICROWAVE',
    'Thirty seconds left on somebody else\'s timer. You will wait. It is the correct thing to do and you resent it.',
    { joy: -1, fight: 0.25, enemy: 'smalltalk', w: 1.2 }),
  O('microwaveclean', 'THE MICROWAVE', ['break_room'], 'MICROWAVE',
    'Someone has cleaned it. Actually cleaned it. There is a note that says "you\'re welcome :)" and no name.',
    { joy: 4, xp: 0.2 }),
  O('noticeboard', 'THE NOTICEBOARD', OFFICE, 'NOTICEBOARD',
    'A fire drill from March, a five-a-side team needing a keeper, and a laminated sheet about the fridge.',
    { xp: 0.4, joy: 1, w: 1.3 }),
  O('noticeguitar', 'THE NOTICEBOARD', OFFICE, 'NOTICEBOARD',
    'Someone is selling a guitar. The card has been there so long the tear-off strips are all still attached.',
    { pay: 0.4, joy: 2 }),
  O('server', 'A SERVER RACK', OFFICE, 'SERVER',
    'It is warm and it hums and one light on it has been amber for as long as anyone can remember.',
    { xp: 0.6, fight: 0.35, enemy: 'conflict' }),
  O('serverfan', 'THE SERVER CUPBOARD', OFFICE, 'SERVER',
    'Warmest place in the building. In winter, people find reasons to file things in here.',
    { joy: 3, xp: 0.3 }),
  O('deskdrawer', 'YOUR DESK', FLOOR, 'DESK',
    'Second drawer down: eleven pens, one of which works, and a birthday card everybody signed for someone who left.',
    { pay: 0.4, joy: 1, w: 1.2 }),
  O('deskplant', 'A DESK', FLOOR, 'DESK',
    'Somebody keeps a small cactus here and has named it. The name is on a label. The label is laminated.',
    { joy: 3 }),

  /* ---------- street ---------- */
  P('flyers', 'SOMEONE WITH FLYERS', OUT,
    'A new place has opened. You take one out of politeness and read it properly at the next crossing.',
    { joy: 1, w: 1.3 }),
  P('busker', 'A BUSKER', OUT,
    'He only knows one song. He plays it beautifully. You have heard it three hundred times and it still works.',
    { pay: -0.3, joy: 4, w: 1.2 }),
  P('elevendogs', 'A DOG WALKER', OUT,
    'Eleven dogs. All calm. He moves like weather. Nobody comments because everyone is busy.',
    { joy: 4 }),
  P('pigeon', 'A PIGEON', OUT,
    'It has one foot and an enormous sense of its own rights. It does not move. You go around.',
    { joy: 2, fight: 0.15, enemy: 'smalltalk', w: 1.3 }),
  P('taichi', 'SOMEONE DOING TAI CHI', ['street', 'park'],
    'In a small square, at eight in the morning, with total unhurried authority. Everything else speeds up around them.',
    { joy: 3 }),
  P('fiveminutes', 'A PERSON ON THE PHONE', OUT,
    '"I’m five minutes away." They are not five minutes away. You watch them walk the wrong way, still saying it.',
    { joy: 2 }),
  P('samples', 'SOMEONE WITH SAMPLES', OUT,
    'A tiny cup of something warm. You take it, thank them, and are unreasonably pleased for a whole block.',
    { joy: 3, item: 'coffee' }),
  P('queue', 'A QUEUE', OUT,
    'For a shop that opens in forty minutes. Six deep. Nobody looks impatient. Something is happening that you do not know about.',
    { xp: 0.4, joy: 1 }),
  O('cornsoup', 'A VENDING MACHINE', OUT, 'VENDING',
    'It sells hot corn soup. In a can. It is exactly what you want and you did not know until now.',
    { item: 'coffee', joy: 3, pay: -0.15, w: 1.3 }),
  O('bikenote', 'A PARKED BICYCLE', OUT, 'LAMP',
    'A note tied to the handlebars says PLEASE MOVE. It has been rained on so often it is now just paper.',
    { joy: -1, xp: 0.2 }),
  O('roadworks', 'ROADWORKS', OUT, 'LAMP',
    'Cones, a hole, a hut. No people, and none for weeks. The hole is doing nothing and has a fence around it.',
    { xp: 0.4, joy: -1 }),
  O('wallcat', 'A CAT ON A WALL', OUT, 'TREE',
    'It permits one stroke. Exactly one. Then it looks away and you are dismissed.',
    { joy: 5, w: 1.4 }),
  O('crane', 'A CRANE', OUT, 'LAMP',
    'It has not moved in a year. A light on it blinks all night. You have started to find it comforting.',
    { joy: 1, xp: 0.3 }),
  O('oldgig', 'A POSTER', OUT, 'FACADE',
    'For a gig that happened last October. Four bands. Someone has written SOLD OUT across it in marker.',
    { joy: 1 }),
  O('shutter', 'A CLOSED SHUTTER', OUT, 'FACADE',
    'It was a bookshop, then a phone shop, then nothing. The bookshop sign is still faintly underneath.',
    { joy: -1, xp: 0.4 }),
  O('umbrella', 'A BROKEN UMBRELLA', OUT, 'BENCH',
    'Inverted, in a bin, spokes out. The universal signal that this morning went badly for somebody.',
    { pay: 0.3 }),

  /* ---------- station ---------- */
  O('departures', 'THE DEPARTURE BOARD', ['station'], 'WHITEBOARD',
    'It flickers between two platforms for the same train. A hundred people stand ready to move either way.',
    { xp: 0.5, fight: 0.25, enemy: 'deadline' }),
  P('running', 'SOMEONE RUNNING', ['station'],
    'They will not make it. They know they will not make it. They are running as a matter of principle.',
    { joy: 2, xp: 0.3 }),
  O('coinmachine', 'A TICKET MACHINE', ['station'], 'VENDING',
    'Coins only. There is a change machine beside it. The change machine is out of order.',
    { fight: 0.3, enemy: 'checkout' }),
  P('upright', 'SOMEONE ASLEEP UPRIGHT', ['station'],
    'Perfectly vertical. Bag on lap. Hands folded. They will wake at exactly their stop. You have never learned how.',
    { joy: 2, xp: 0.4 }),
  O('lostglove', 'A GLOVE ON A RAILING', ['station'], 'LAMP',
    'Placed, not dropped — someone put it there so its owner could find it. Nobody did. It is still waiting.',
    { joy: 2 }),

  /* ---------- market and konbini ---------- */
  P('comparing', 'SOMEONE COMPARING', SHOP,
    'Two tins. Identical brand, price and weight. This has been going on a while and shows no sign of resolving.',
    { joy: 1, fight: 0.2, enemy: 'groceries' }),
  P('negotiating', 'A CHILD NEGOTIATING', SHOP,
    'They have opened with everything and are prepared to settle for one thing. The parent knows. The child knows the parent knows.',
    { joy: 4, w: 1.2 }),
  O('selfcheckout', 'A SELF-CHECKOUT', SHOP, 'COUNTER',
    'Unexpected item in the bagging area. There is no item. There has never been an item.',
    { fight: 0.55, enemy: 'checkout', w: 1.3 }),
  O('lastchicken', 'THE LAST CHICKEN', ['market'], 'FREEZER',
    'One left under the hot lamp. Two people are approaching it at casual speed from opposite ends of the aisle.',
    { fight: 0.35, enemy: 'groceries', item: 'bento' }),
  O('badwheel', 'A TROLLEY', ['market'], 'SHELF',
    'One wheel does its own thing. You take it anyway. You always take it anyway.',
    { joy: -1, xp: 0.3 }),
  P('lateshop', 'SOMEONE SHOPPING AT 11PM', SHOP,
    'A full weekly shop. Calm, unhurried. This is clearly the correct time to do it and everyone else is wrong.',
    { joy: 2, xp: 0.4 }),
  O('reduced', 'THE REDUCED SHELF', ['market'], 'SHELF',
    'A man with a label gun is being followed at a respectful distance by four people pretending to look at bread.',
    { pay: 0.6, item: 'bento', w: 1.3 }),
  O('shopcat', 'A SHOP CAT', ['konbini'], 'SHELF',
    'Asleep on the newspapers, which nobody buys, in the only patch of sun in the building.',
    { joy: 5 }),
  P('headphones', 'SOMEONE RESTOCKING', SHOP,
    'Headphones on, entirely in their own world, facing tins with the precision of a watchmaker.',
    { joy: 2, xp: 0.3 }),
  O('bagofice', 'A BAG OF ICE', SHOP, 'FREEZER',
    'Nobody has ever bought it. It has frozen, thawed and refrozen into a single enormous shape.',
    { joy: 1 }),
  O('magazines', 'THE MAGAZINE RACK', ['konbini'], 'SHELF',
    'A man is reading one cover to cover. He will not buy it. The staff have made peace with this.',
    { joy: 2, xp: 0.3 }),
  O('hotcase', 'THE HOT CASE', ['konbini'], 'COUNTER',
    'Things on sticks, under a light, at an hour that makes them seem like an excellent idea.',
    { item: 'bento', pay: -0.2, joy: 3 }),

  /* ---------- park ---------- */
  O('bestdog', 'A DOG', ['park'], 'GRASS',
    'It is having the best day of anyone in this city. It has found a stick. The stick is enormous.',
    { joy: 6, w: 1.5 }),
  P('ducks', 'SOMEONE FEEDING DUCKS', ['park'],
    'There is a sign asking them not to. They have brought proper duck food in a tub, which feels like a loophole.',
    { joy: 3 }),
  P('detector', 'A MAN WITH A METAL DETECTOR', ['park'],
    'He has found a bottle cap and two coins. He is delighted. He shows you. You are also, unexpectedly, delighted.',
    { pay: 0.4, joy: 4 }),
  P('samepage', 'SOMEONE READING', ['park'],
    'They have been on the same page for twenty minutes. They are not reading. They are just somewhere else for a bit.',
    { joy: 3, xp: 0.3 }),
  O('outdoorgym', 'OUTDOOR GYM EQUIPMENT', ['park'], 'BENCH',
    'Yellow, sun-bleached, faintly squealing. A man in jeans is doing a very slow cross-trainer.',
    { joy: 2 }),
  O('fullbin', 'A BIN', ['park'], 'LAMP',
    'Full since the weekend. Everyone has balanced their rubbish on top in a small, polite tower.',
    { joy: -1, xp: 0.2 }),
  P('bike', 'A CHILD LEARNING TO CYCLE', ['park'],
    'A parent jogs behind holding nothing at all, having let go some time ago, saying "I’ve got you."',
    { joy: 6, w: 1.2 }),
  P('photoshoot', 'A PHOTO SHOOT', ['park'],
    'Two people and a ring light, taking this extremely seriously, by the duck pond.',
    { joy: 2 }),
  O('plaque', 'A BENCH', ['park'], 'BENCH',
    'A small plaque: "HE LOVED THIS VIEW." It is a good view. You sit for a minute on his behalf.',
    { joy: 5, xp: 0.4, w: 1.2 }),
  P('runner', 'A RUNNER', ['park'],
    'They nod. You nod. Neither of you knows the other. It is the entire relationship and it is perfect.',
    { joy: 3 }),

  /* ---------- izakaya ---------- */
  P('ordersforall', 'SOMEONE ORDERING', ['izakaya'],
    'They have ordered for the table without asking. Everything that arrives is better than what you would have chosen.',
    { joy: 4, pay: -0.4, w: 1.3 }),
  P('honest', 'A COLLEAGUE, HONEST', ['izakaya'],
    'Two drinks in, they tell you they think you are good at this. In the morning neither of you will bring it up. You will remember it for years.',
    { joy: 6, xp: 0.6 }),
  O('karaoke', 'A KARAOKE MACHINE', ['izakaya'], 'TV',
    'Someone has queued nine songs. Someone else has queued one, and is waiting with enormous patience.',
    { joy: 4, pay: -0.3 }),
  P('owner', 'THE OWNER', ['izakaya'],
    'She remembers your order, and that you do not like coriander. You have been here four times.',
    { joy: 5, item: 'bento', w: 1.2 }),
  P('cryinghappy', 'SOMEONE CRYING HAPPILY', ['izakaya'],
    'A leaving do. They are fine. They keep saying they are fine and hugging people, which is how you can tell they are fine.',
    { joy: 3 }),
  O('extraplate', 'A PLATE YOU DID NOT ORDER', ['izakaya'], 'TABLE',
    'It arrives anyway. The kitchen made too many. Nobody is charged. It is the best thing on the table.',
    { item: 'sandwich', joy: 4 }),
  P('twoasleep', 'TWO SALARYMEN', ['izakaya'],
    'Both asleep, both upright, ties loosened to exactly the same angle. A matched set.',
    { joy: 2, xp: 0.3 }),
  O('thebill', 'THE BILL', ['izakaya'], 'COUNTER',
    'It sits in the middle of the table in a small wooden box. Everyone is looking at everything else.',
    { pay: -0.8, joy: 1, fight: 0.2, enemy: 'expenses' }),
  P('regular', 'A REGULAR', ['izakaya'],
    'He talks to everyone, including the kitchen, including you. By the end you have agreed to something and you are not sure what.',
    { joy: 3, xp: 0.4 }),
  O('luckycat', 'A LUCKY CAT', ['izakaya', 'konbini'], 'LANTERN',
    'Its arm is broken and has been taped in the raised position, so it is permanently, aggressively lucky.',
    { pay: 0.7, joy: 3, w: 1.2 }),

  /* ---------- apartment ---------- */
  O('fridgehum', 'THE FRIDGE', ['apartment'], 'FREEZER',
    'It hums. You have lived with this hum so long that silence would be alarming.',
    { joy: 2 }),
  O('parcel', 'A PARCEL', ['apartment'], 'TABLE',
    'You did not order it. It is addressed to you. You open it. It is a thing you ordered so long ago you had forgotten wanting it.',
    { joy: 5, item: 'energy', w: 1.2 }),
  O('neighbour', 'THE WALL', ['apartment'], 'WALL',
    'Your neighbour is watching something with a laugh track. The laughs come at intervals. You find yourself waiting for them.',
    { joy: 1 }),
  O('houseplant', 'A HOUSEPLANT', ['apartment'], 'PLANT',
    'You have kept it alive for two years. This is the longest you have kept anything alive and you are quietly proud.',
    { joy: 4 }),
  O('laundry', 'THE WASHING MACHINE', ['apartment'], 'FREEZER',
    'Eleven minutes remaining. It has said eleven minutes remaining for nineteen minutes.',
    { joy: -1, xp: 0.3, fight: 0.15, enemy: 'deadline' }),
  O('cabledrawer', 'A DRAWER', ['apartment'], 'TABLE',
    'Cables. Chargers for devices you no longer own. A remote for something. You close it again.',
    { pay: 0.4, joy: 1 }),
  O('twoam', 'THE WINDOW', ['apartment'], 'WALL',
    'At night the city is just lit rectangles, most of them empty, some of them not. Somebody else is also up.',
    { joy: 3, xp: 0.4 }),
  O('reflection', 'YOUR REFLECTION', ['apartment'], 'TV',
    'In the dark screen. Tie still on. You take it off. That is the whole event and it helps.',
    { joy: 4, w: 1.2 }),
];

export const INTERACTION_BY_ID = Object.fromEntries(INTERACTIONS.map((i) => [i.id, i]));

/** Everything that can appear in a given area kind. */
export function interactionsFor(zone, kind = null) {
  return INTERACTIONS.filter((i) => i.zones.includes(zone) && (kind === null || i.kind === kind));
}

export const INTERACTION_COUNT = INTERACTIONS.length;
